### PR TITLE
Add minimal M120 hydrography example

### PR DESCRIPTION
**Pull request by willirath**
Test on binder: [Binder](https://mybinder.org/v2/gh/esm-vfc/esm-vfc-workflows/add-M120-workflow?urlpath=lab/)

### CODE REVIEW

**Comment by willirath** [comment]
@benbovy This minimal example illustrates some of the obstacles we'll face with the NEMO data

- lack CF compliance in coord definitions
- non-monotonic 2-dimensional latitude and longitude fields

and it also could be a nice test-bed for 2d coordinate selection in Xarrray.

**Comment by willirath** [comment]
Todo: Use `fetch_zenodo_catalog` from https://github.com/ESM-VFC/esm-vfc-catalogs as soon as https://github.com/ESM-VFC/esm-vfc-catalogs/pull/5 is merged.

**Comment by willirath** [comment]
@benbovy I only now realise that the netCDF error you saw with `m120_vs_NEMO_FOCI_hydrography/visualize_m120_positions.ipynb` might have to do with the fact that you did not pre-fetch the data? I need to clarify this or just do the pre-fetching in the same notebook for now.

**Comment by benbovy** [comment]
Yep, sorry, after running the prefetch_data notebook everything run fine.

**Comment by willirath** [comment]
Todo: Install catalog tools in compute env.

**Pull request merged**
